specifications:
- name: Template
  status: revision
  spec_type: Profile
  use_cases_url:
  version: 0.0.1
  parent_type: Thing
  spec_mapping_url: https://docs.google.com/spreadsheets/d/1-Q928CHdkvfsqivFV-oDSKrJDlWx4FIbXYCAcEJyZWY/edit#gid=1483018794
